# Generated by Django 3.2.13 on 2022-06-11 01:58

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Alvo',
                'verbose_name_plural': 'Alvos',
                'ordering': ['nome'],
            },
        ),
    ]
